### ISSUE TITLE
fstab lines without absolute path

### ISSUE THREAD

**Issue by gronke** [bsdci/libioc#613]
When libioc parses an fstab line with a non-absolute source path, parsing the file fails.

```
$ ioc create gronke
$ echo "tmpfs /tmp tmpfs rw,mode=777 0 0" >> /iocage/jails/gronke/fstab
```

```python3
>>> libioc.Jail("gronke").fstab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/src/ioc/libioc/Jail.py", line 2206, in __getattribute__
    return object.__getattribute__(self, key)
  File "/usr/local/src/ioc/libioc/Jail.py", line 144, in fstab
    host=jail.host
  File "/usr/local/src/ioc/libioc/Config/Jail/File/Fstab.py", line 181, in __init__
    self.read_file()
  File "/usr/local/src/ioc/libioc/Config/Jail/File/Fstab.py", line 305, in read_file
    self._read_file_handle(f)
  File "/usr/local/src/ioc/libioc/Config/Jail/File/Fstab.py", line 319, in _read_file_handle
    self.parse_lines(f.read())
  File "/usr/local/src/ioc/libioc/Config/Jail/File/Fstab.py", line 290, in parse_lines
    "source": libioc.Types.AbsolutePath(source),
  File "/usr/local/src/ioc/libioc/Types.py", line 40, in __init__
    raise TypeError(f"Invalid value for AbsolutePath: {sequence}")
TypeError: Invalid value for AbsolutePath: tmpfs
```

**Comment by igalic** [comment]
`mode=777` is bad for `/tmp`.
you want `mode=1777`

**Comment by gronke** [comment]
@igalic it has no effect on reproduction of this bug, but good catch :)
